apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-prod

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-prod.yaml
  - service-prod.yaml
  - ingressroute-prod.yaml
  - certificate.yaml

labels:
- pairs:
    app: portfolio
    environment: production
    managed-by: kustomize
    version: v1
  includeSelectors: false

commonAnnotations:
  created-by: portfolio-devops
  managed-version: "1.0"

images:
- name: joannegton/portfolio
  newName: joannegton/portfolio
  newTag: v1.0.0

replicas:
- name: portfolio-app
  count: 3
