apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tls
  namespace: portfolio-prod
  labels:
    app: portfolio
    environment: production
spec:
  secretName: portfolio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - joannegton.com
  - www.joannegton.com
